services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: database
    volumes:
      - D:\Services\Nextcloud:/var/www/html

  database:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - D:\Services\Database:/var/lib/mysql
